import Head from "next/head";
import Link from "next/link";

export default function Home({ pokemons }) {
  return (
    <>
      <Head>
        <title>Elis Pokemons</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Pokemons!</h1>

      <ul>
        {pokemons.map((pokemon) => (
          <li key={pokemon.name}>
            <Link href={`pokemons/${pokemon.name}`}>{pokemon.name}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}

export async function getStaticProps() {
  const uri = "https://pokeapi.co/api/v2/pokemon";
  const res = await fetch(uri);
  const data = await res.json();

  return {
    props: {
      pokemons: data.results,
    },
  };
}
